### ISSUE TITLE
How to modify the gradient color under a label

### ISSUE THREAD

**Issue by Yakumo-Yukari** [EliverLara/Kimi#2]
Hi thanks for the theme, very beautiful
Excuse me, I want to modify this gradient color. Where do I need to modify it?

![img 2019-12-28 15 21 41](https://user-images.githubusercontent.com/12076232/71540521-a17e8000-2986-11ea-9147-e89ca9e92322.png)

**Comment by EliverLara** [comment]
Hi, I have refactorized the code a bit, now it's easy to modify those colors by changing the `$selected-tab-gradient-start` and `$selected-tab-gradient-end` variables on the `gtk-3.0_colors.scss `file, once you change that just recompile the theme.

**Comment by Yakumo-Yukari** [comment]
> Hi, I have refactorized the code a bit, now it's easy to modify those colors by changing the `$selected-tab-gradient-start` and `$selected-tab-gradient-end` variables on the `gtk-3.0_colors.scss `file, once you change that just recompile the theme.

Okay thank you
