### ISSUE TITLE
Icons not changing.

### ISSUE THREAD

**Issue by VandanUbuntu** [EliverLara/Kimi#3]
I have followed all the instructions on the ReadMe file. The theme applied fine. But the Icons didn't change. 
![image](https://user-images.githubusercontent.com/60042992/72777869-fbb7eb80-3c7b-11ea-8713-3a6066cfcd6e.png)

How do I get the icons to change to the Kimi icon(the purple ones).

**Comment by EliverLara** [comment]
Hi, this theme does not change the icon theme , [these](https://github.com/EliverLara/Kimi/files/4109711/Kimi.zip) are the ones I used in my screenshot.
