### ISSUE TITLE
Pale Buttons

### ISSUE THREAD

**Issue by mertertin** [EliverLara/Kimi#4]
Colored create, accept, save and cancel buttons look pale and it gives a signal like I can't click on it. Can you please make it saturated? I know this isn't a serious issue but this theme is a major reason I enjoy GNU/Linux. Thanks for your effort.

![Screenshot from 2020-01-27 20-07-41](https://user-images.githubusercontent.com/43197853/73196884-792ea080-4141-11ea-9b71-bb41bcc67f3a.png)

**Comment by EliverLara** [comment]
I've improved that.
